@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "StaffMember#setDepartment(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "StaffMember",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1706522830 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main2390489XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_406024000 { 
   	label=StaffRecordSystem
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1570050834 { 
   	label=StaffRecordSystem
	labeljust=l
	fillcolor=white
	style=filled
   
   StaffRecordSystem406024000XXXupdateStaffMember1026393664[
	label="+ updateStaffMember()"
	style=filled
	fillcolor=white
	tooltip="StaffRecordSystem

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_636893562 { 
   	label=StaffMember
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1136378630 { 
   	label=StaffMember
	labeljust=l
	fillcolor=white
	style=filled
   
   StaffMember636893562XXXsetDepartment1808118735[
	label="+ setDepartment()"
	style=filled
	fillcolor=white
	tooltip="StaffMember

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

'edges    
Main2390489XXXmain1859653459 -> StaffRecordSystem406024000XXXupdateStaffMember1026393664;
StaffRecordSystem406024000XXXupdateStaffMember1026393664 -> StaffMember636893562XXXsetDepartment1808118735;
    
}
@enduml